[package]
name = "rad-init"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1.0"
librad = "0"
rad-clib = "0"
rad-profile = "0"
radicle-tools = { path = "../" }
rad-terminal = { path = "../terminal" }
rad-common = { path = "../common" }
