[package]
name = "radicle-tools"
version = "0.0.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
colored = { version = "1.9" }
atty = { version = "0.2" }
log = { version = "0.4", features = ["std"] }
librad = { version = "0" }
rad-profile = { version = "0" }

[workspace]
members = [
  "anchor",
  "account",
  "safe-transaction-client",
  "terminal",
  "common",
  "checkout",
  "ens",
  "auth",
  "help",
  "rad",
  "init",
  "push",
  "sync",
  "show",
  "track",
  "untrack",
  "proof-generator",
  "git-remote-rad",
  "authorized-keys"
]

[patch.crates-io.link-crypto]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.link-identities]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.radicle-git-helpers]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.librad]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.rad-clib]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.rad-profile]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.rad-exe]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.radicle-git-ext]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.rad-identities]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.thrussh-encoding]
git = "https://github.com/FintanH/thrussh.git"
branch = "generic-agent"
