[package]
name = "radicle-tools"
version = "0.0.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
lexopt = "0.2"
colored = { version = "1.9" }
atty = { version = "0.2" }
log = { version = "0.4", features = ["std"] }
librad = { version = "0" }
rad-exe = { version = "0" }
rad-profile = { version = "0" }
rad-account = { path = "./account" }
rad-auth = { path = "./auth" }
rad-common = { path = "./common" }
rad-terminal = { path = "./terminal" }
rad-init = { path = "./init" }
rad-show = { path = "./show" }
rad-push = { path = "./push" }
rad-sync = { path = "./sync" }
rad-ens = { path = "./ens" }
rad-checkout = { path = "./checkout" }
rad-track = { path = "./track" }
rad-untrack = { path = "./untrack" }
rad-help = { path = "./help" }
rad-ls = { path = "./ls" }
rad-rm = { path = "./rm" }
ethers = { version = "0.6.2" }
link-identities = { version = "0" }
radicle-git-helpers = { version = "0" }
url = { version = "*" }
tokio = { version = "1.10", features = ["rt"] }
futures = { version = "0.3" }

[workspace]
members = [
  "anchor",
  "account",
  "safe-transaction-client",
  "terminal",
  "common",
  "checkout",
  "ens",
  "auth",
  "help",
  "rad",
  "init",
  "ls",
  "rm",
  "push",
  "sync",
  "show",
  "track",
  "untrack",
  "proof-generator",
  "authorized-keys"
]

[patch.crates-io.link-crypto]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.link-identities]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.radicle-git-helpers]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.librad]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.rad-clib]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.rad-profile]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.rad-exe]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.radicle-git-ext]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.rad-identities]
git = "https://github.com/radicle-dev/radicle-link"
rev = "b51ed772fe4ec2ae4fdb4e95bac0e3271be197c8"

[patch.crates-io.thrussh-encoding]
git = "https://github.com/FintanH/thrussh.git"
branch = "generic-agent"
