[package]
name = "rad"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Radicle top-level command"

[dependencies]
anyhow = "1.0"
librad = "0"
lexopt = "0.1"
rad-clib = "0"
rad-exe = "0"
rad-profile = "0"
radicle-tools = { path = "../" }
rad-terminal = { path = "../terminal" }
rad-common = { path = "../common" }
rad-help = { path = "../help" }
