[package]
name = "rad-help"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Radicle tools help"

[dependencies]
anyhow = "1.0"
librad = "0"
lexopt = "0.2"
rad-clib = "0"
rad-profile = "0"
rad-terminal = { path = "../terminal" }
rad-common = { path = "../common" }
rad-show = { path = "../show" }
rad-ls = { path = "../ls" }
rad-track = { path = "../track" }
rad-untrack = { path = "../untrack" }
rad-init = { path = "../init" }
rad-auth = { path = "../auth" }
rad-clone = { path = "../clone" }
rad-account = { path = "../account" }
rad-checkout = { path = "../checkout" }
rad-push = { path = "../push" }
rad-sync = { path = "../sync" }
rad-ens = { path = "../ens" }
