[package]
name = "rad-issue"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Manage radicle issues"

[dependencies]
automerge = { version = "0" }
lexopt = { version = "0.2" }
anyhow = { version = "1.0" }
lazy_static = { version = "1.4.0" }
librad = { version = "0" }
radicle-terminal = { path = "../terminal" }
radicle-common = { path = "../common" }
serde_json = { version = "1.0" }
serde = { version = "1.0" }
