[package]
name = "rad-common"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
base64 = "0.13"
byteorder = "1.4"
dialoguer = "0.9.0"
indicatif = "0.16.2"
git2 = "0.13"
librad = { version = "0" }
rad-clib = { version = "0" }
rad-profile = { version = "0" }
rad-identities = { version = "0" }
rad-terminal = { path = "../terminal" }
radicle-git-ext = { version = "0" }
url = { version = "*" }
sha2 = { version = "*" }
