[package]
name = "rad-terminal"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
dialoguer = "0.9.0"
indicatif = "0.16.2"
console = "0.15"
librad = { version = "0" }
rad-clib = { version = "0" }
rad-profile = { version = "0" }
thiserror = "1.0"
