name: Package

on:
  push:
    branches:
      - master
      - debug/*

jobs:
  deb:
    name: Create a .deb package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure build cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ubuntu-latest-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update dependencies
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y asciidoctor
      - name: script
        run: .github/build-man-page.bash radicle-tools.1.adoc >radicle-tools.1.gz
        shell: bash
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - run: cargo install cargo-deb
      - run: cargo deb
      - uses: actions/upload-artifact@v2
        with:
          name: radicle-tools
          path: target/debian/*.deb
